[book]
title = "Ahmed's Professional Articles"
authors = []
language = "en"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]
optional = true

[output]

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["custom.css"]
